/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as BookShelfRouteImport } from './routes/book/shelf'
import { Route as ReaderPathRouteImport } from './routes/reader/$path'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const BookShelfRoute = BookShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => BookRoute,
} as any)
const ReaderPathRoute = ReaderPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => ReaderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/reader': typeof ReaderRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/book/shelf': typeof BookShelfRoute
  '/reader/$path': typeof ReaderPathRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/reader': typeof ReaderRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/book/shelf': typeof BookShelfRoute
  '/reader/$path': typeof ReaderPathRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/reader': typeof ReaderRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/book/shelf': typeof BookShelfRoute
  '/reader/$path': typeof ReaderPathRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/reader'
    | '/auth/login'
    | '/auth/register'
    | '/book/shelf'
    | '/reader/$path'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/reader'
    | '/auth/login'
    | '/auth/register'
    | '/book/shelf'
    | '/reader/$path'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/book'
    | '/reader'
    | '/auth/login'
    | '/auth/register'
    | '/book/shelf'
    | '/reader/$path'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BookRoute: typeof BookRouteWithChildren
  ReaderRoute: typeof ReaderRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/book/shelf': {
      id: '/book/shelf'
      path: '/shelf'
      fullPath: '/book/shelf'
      preLoaderRoute: typeof BookShelfRouteImport
      parentRoute: typeof BookRoute
    }
    '/reader/$path': {
      id: '/reader/$path'
      path: '/$path'
      fullPath: '/reader/$path'
      preLoaderRoute: typeof ReaderPathRouteImport
      parentRoute: typeof ReaderRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BookRouteChildren {
  BookShelfRoute: typeof BookShelfRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookShelfRoute: BookShelfRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface ReaderRouteChildren {
  ReaderPathRoute: typeof ReaderPathRoute
}

const ReaderRouteChildren: ReaderRouteChildren = {
  ReaderPathRoute: ReaderPathRoute,
}

const ReaderRouteWithChildren =
  ReaderRoute._addFileChildren(ReaderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BookRoute: BookRouteWithChildren,
  ReaderRoute: ReaderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
