/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as BookShelfRouteImport } from './routes/book/shelf'
import { Route as ReaderBookIdRouteImport } from './routes/reader/$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const BookShelfRoute = BookShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => BookRoute,
} as any)
const ReaderBookIdRoute = ReaderBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => ReaderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/reader': typeof ReaderRouteWithChildren
  '/book/shelf': typeof BookShelfRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/reader': typeof ReaderRouteWithChildren
  '/book/shelf': typeof BookShelfRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/reader': typeof ReaderRouteWithChildren
  '/book/shelf': typeof BookShelfRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book' | '/reader' | '/book/shelf' | '/reader/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book' | '/reader' | '/book/shelf' | '/reader/$bookId'
  id: '__root__' | '/' | '/book' | '/reader' | '/book/shelf' | '/reader/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  ReaderRoute: typeof ReaderRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/shelf': {
      id: '/book/shelf'
      path: '/shelf'
      fullPath: '/book/shelf'
      preLoaderRoute: typeof BookShelfRouteImport
      parentRoute: typeof BookRoute
    }
    '/reader/$bookId': {
      id: '/reader/$bookId'
      path: '/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof ReaderBookIdRouteImport
      parentRoute: typeof ReaderRoute
    }
  }
}

interface BookRouteChildren {
  BookShelfRoute: typeof BookShelfRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookShelfRoute: BookShelfRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface ReaderRouteChildren {
  ReaderBookIdRoute: typeof ReaderBookIdRoute
}

const ReaderRouteChildren: ReaderRouteChildren = {
  ReaderBookIdRoute: ReaderBookIdRoute,
}

const ReaderRouteWithChildren =
  ReaderRoute._addFileChildren(ReaderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  ReaderRoute: ReaderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
